repos:

  - repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.9
        exclude: >
          (?x)^(
            scripts/gen-docs-index|
          )$

  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.2.3
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        exclude: deploy/
      - id: debug-statements
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: flake8
      - id: trailing-whitespace

  - repo: https://github.com/igorshubovych/markdownlint-cli.git
    rev: v0.41.0
    hooks:
      - id: markdownlint
        entry: markdownlint --ignore .github/*.md
